baseurl = "/Blogdown/"
languageCode = "en-us"
title = "Kyle's Website"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
publishDir = "docs"


[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Bio"
    url = "/Bio/"
    weight = 2
   
[[menu.main]]
    name = "Research"
    url = "/Research/"
    weight = 1

[[menu.main]]
    name = "Teaching"
    url = "/Teaching/"
    weight = 3
   

[params]
    description = "Kyle Leathers Personal Website"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

